### ISSUE TITLE
Account ID in provider config

### ISSUE THREAD

**Issue by trietsch** [spotify/gcp-aws-iam-federation-webidentity#1]
Hi, thanks for sharing this, useful! I did notice that the provider config for [AWS contains a profile ID](https://github.com/spotify/gcp-aws-iam-federation-webidentity/blob/main/terraform/main.tf#L41) that seems to be containing an AWS account ID. It's not necessarily a secret, but it's better to omit them here as this is meant as a Terraform module.

**Comment by Monrava** [comment]
Thanks for flagging this!
It was a testing account ID which we've now removed :)
We'll also remove it from the commit history.
